apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "evaluation-runner.fullname" . }}
  labels:
    {{- include "evaluation-runner.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/customConfig: {{ sha256sum (print (tpl (toYaml .Values.runnerConfig) $)) }}
      labels:
        {{- include "evaluation-runner.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: {{ tpl .Values.hostNetwork . }}
      dnsPolicy: {{ tpl .Values.dnsPolicy . }}
      dnsConfig:
        nameservers:
        {{- with .Values.nameservers }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
      imagePullSecrets:
        {{- with .Values.imagePullSecrets }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: {{ .Values.restartPolicy }}
      containers:
        - name: evaluation-runner
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ tpl .Values.image.repository . }}:{{ tpl .Values.image.tag . }}"
          imagePullPolicy: "{{ tpl .Values.image.pullPolicy . }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          command:
          - "/bin/bash"
          - "-c"
          - |
            source /root/venv/bin/activate && python3 -u /root/eval-runner/eval-runner.py || tail -f /dev/null
          volumeMounts:
          - name: runner-config
            mountPath: /etc/eval-runner.yaml
            subPath: eval-runner.yaml
      volumes:
        - name: runner-config
          configMap:
            name: {{ include "evaluation-runner.fullname" . }}
            items:
            - key: runnerConfig
              path: eval-runner.yaml
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  backoffLimit: 0  
